server:
  error:    include-stacktrace: on-param
    
spring:  datasource:    url: jdbc:mysql://localhost:3306/miniautorizador?userSSL=false?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true 
    username: root
    password: 
  jpa:    hibernate:      ddl-auto: create
      generate-ddl: true
      show-sql: true 
       
      